export const HEADER_MENU_ITEMS = [
  {
    title: 'navigation.about',
    url: '/about'
  },
  {
    title: 'navigation.rooms',
    url: '/rooms'
  },
  {
    title: 'navigation.gallery',
    url: '/gallery'
  },
  {
    title: 'navigation.experiences',
    url: '/experiences'
  },
  {
    title: 'navigation.contact',
    url: '/contact'
  }
];

export const LANGUAGES = [
  {
    title: 'en',
    value: 'en',
    label: 'english'
  },
  {
    title: 'tr',
    value: 'tr',
    label: 'turkish'
  }
];

export const ROOMS = [
  {
    id: '1',
    title: 'room1',
    image: 'oda_1/oda1-min.jpg',
    name: 'Zeus',
    description: 'room1Description',
    bookingInformation: {
      price: '-',
      guestNumber: 2,
      sleeps: ['kingBed', 'sofa'],
      bathroom: 1,
      size: 40,
      features: [
        'wifi',
        'nonSmoking',
        'airConditioning',
        'heating',
        'tv',
        'minibar',
        'safeBox',
        'hairDryer',
        'roomService',
        'dailyCleaning',
        'towel',
        'bathrobe',
        'slippers',
        'toiletries',
        'balcony',
      ]
    },
    images: [
      'oda_1/oda1-1-min.jpg',
      'oda_1/oda1-2-min.jpg',
      'oda_1/oda1-3-min.jpg',
      'oda_1/oda1-4-min.jpg',
      'oda_1/oda1-5-min.jpg',
      'oda_1/oda1-6-min.jpg',
      'oda_1/oda1-min.jpg',
      'oda_1/wc-1-min.jpg',
      'oda_1/wca-2-min.jpg',
      'oda_1/wca-3-min.jpg',
      'oda_1/wca-4-min.jpg',
      'oda_1/wca-5-min.jpg',
    ]
  },
  {
    id: '2',
    title: 'room2',
    name: 'Hera',
    image: 'oda_2/oda2-1-min.jpg',
    description: 'room1Description',
    bookingInformation: {
      price: '-',
      guestNumber: 2,
      sleeps: ['kingBed'],
      bathroom: 1,
      size: 25,
      features: [
        'wifi',
        'nonSmoking',
        'airConditioning',
        'heating',
        'tv',
        'minibar',
        'safeBox',
        'hairDryer',
        'roomService',
        'dailyCleaning',
        'towel',
        'bathrobe',
        'slippers',
        'toiletries',
        'balcony',
      ]
    },
    images: [
      'oda_2/oda2-1-min.jpg',
      'oda_2/oda2-2-min.jpg',
      'oda_2/oda2-3-min.jpg',
      'oda_2/oda2-4-min.jpg',
      'oda_2/oda2-5-min.jpg',
      'oda_2/oda2-6-min.jpg',
      'oda_2/wcb-1-min.jpg',
      'oda_2/wcb-2-min.jpg',
      'oda_2/wcb-3-min.jpg',
    ]
  },
  {
    id: '3',
    name: 'tenedos',
    title: 'room3',
    image: 'oda_3/oda3-1-min.jpg',
    description: 'room3Description',
    bookingInformation: {
      price: '-',
      guestNumber: 2,
      sleeps: ['kingBed', 'sofa'],
      bathroom: 1,
      size: 30,
      features: [
        'wifi',
        'nonSmoking',
        'airConditioning',
        'heating',
        'tv',
        'minibar',
        'safeBox',
        'hairDryer',
        'roomService',
        'dailyCleaning',
        'towel',
        'bathrobe',
        'slippers',
        'toiletries',
        'balcony',
      ]
    },
    images: [
      'oda_3/oda3-1-min.jpg',
      'oda_3/oda3-2-min.jpg',
      'oda_3/oda3-3-min.jpg',
      'oda_3/oda3-4-min.jpg',
      'oda_3/oda3-6-min.jpg',
      'oda_3/oda3-7-min.jpg',
      'oda_3/oda3-8-min.jpg',
      'oda_3/oda3-9-min.jpg',
      'oda_3/wcc-1-min.jpg',
      'oda_3/wcc-2-min.jpg',
      'oda_3/wcc-3-min.jpg',
    ]
  },
  {
    id: '4',
    title: 'room4',
    name: 'tenes',
    image: 'oda_4/oda4-1-min.jpg',
    description: 'room4Description',
    bookingInformation: {
      price: '-',
      guestNumber: 2,
      sleeps: ['kingBed', 'sofa'],
      bathroom: 1,
      size: 30,
      features: [
        'wifi',
        'nonSmoking',
        'airConditioning',
        'heating',
        'tv',
        'minibar',
        'safeBox',
        'hairDryer',
        'roomService',
        'dailyCleaning',
        'towel',
        'bathrobe',
        'slippers',
        'toiletries',
        'balcony',
      ]
    },
    images: [
      'oda_4/oda4-1-min.jpg',
      'oda_4/oda4-2-min.jpg',
      'oda_4/oda4-3-min.jpg',
      'oda_4/oda4-4-min.jpg',
      'oda_4/oda4-5-min.jpg',
      'oda_4/oda4-6-min.jpg',
      'oda_4/oda4-7-min.jpg',
      'oda_4/oda4-8-min.jpg',
      'oda_4/oda4-9-min.jpg',
      'oda_4/oda4-10-min.jpg',
      'oda_4/wcd-1-min.jpg',
      'oda_4/wcd-2-min.jpg',
      'oda_4/wcd-3-min.jpg',
    ]
  },
  {
    id: '5',
    name: 'ilyada',
    title: 'room5',
    image: 'oda_3/oda3-1-min.jpg',
    description: 'room5Description',
    bookingInformation: {
      price: '-',
      guestNumber: 2,
      sleeps: ['kingBed', 'sofa'],
      bathroom: 1,
      size: 30,
      features: [
        'wifi',
        'nonSmoking',
        'airConditioning',
        'heating',
        'tv',
        'minibar',
        'safeBox',
        'hairDryer',
        'roomService',
        'dailyCleaning',
        'towel',
        'bathrobe',
        'slippers',
        'toiletries',
        'balcony',
      ]
    },
    images: [
      'oda_3/oda3-9-min.jpg',
      'oda_3/oda3-3-min.jpg',
      'oda_3/oda3-1-min.jpg',
      'oda_3/oda3-4-min.jpg',
      'oda_3/oda3-2-min.jpg',
      'oda_3/oda3-8-min.jpg',
      'oda_3/oda3-6-min.jpg',
      'oda_3/oda3-7-min.jpg',
      'oda_3/wcc-1-min.jpg',
      'oda_3/wcc-2-min.jpg',
      'oda_3/wcc-3-min.jpg',
    ]
  },
];

export const GALLERY_IMAGES = [
  'homepage-1-min.jpg',
  'homepage-2-min.jpg',
  'homepage-3-min.jpg',
  'homepage-4-min.jpg',
  'homepage-5-min.jpg',
  'homepage-6-min.jpg',
  'oda_1/oda1-1-min.jpg',
  'oda_1/oda1-2-min.jpg',
  'oda_1/oda1-3-min.jpg',
  'oda_1/oda1-4-min.jpg',
  'oda_1/oda1-5-min.jpg',
  'oda_1/oda1-6-min.jpg',
  'oda_1/oda1-min.jpg',
  'oda_1/wc-1-min.jpg',
  'oda_1/wca-2-min.jpg',
  'oda_1/wca-3-min.jpg',
  'oda_1/wca-4-min.jpg',
  'oda_1/wca-5-min.jpg',
  'oda_2/oda2-1-min.jpg',
  'oda_2/oda2-2-min.jpg',
  'oda_2/oda2-3-min.jpg',
  'oda_2/oda2-4-min.jpg',
  'oda_2/oda2-5-min.jpg',
  'oda_2/oda2-6-min.jpg',
  'oda_2/wcb-1-min.jpg',
  'oda_2/wcb-2-min.jpg',
  'oda_2/wcb-3-min.jpg',
  'oda_3/oda3-1-min.jpg',
  'oda_3/oda3-2-min.jpg',
  'oda_3/oda3-3-min.jpg',
  'oda_3/oda3-4-min.jpg',
  'oda_3/oda3-5-min.jpg',
  'oda_3/oda3-6-min.jpg',
  'oda_3/oda3-7-min.jpg',
  'oda_3/oda3-8-min.jpg',
  'oda_3/oda3-9-min.jpg',
  'oda_3/wcc-1-min.jpg',
  'oda_3/wcc-2-min.jpg',
  'oda_3/wcc-3-min.jpg',
  'oda_4/oda4-1-min.jpg',
  'oda_4/oda4-2-min.jpg',
  'oda_4/oda4-3-min.jpg',
  'oda_4/oda4-4-min.jpg',
  'oda_4/oda4-5-min.jpg',
  'oda_4/oda4-6-min.jpg',
  'oda_4/oda4-7-min.jpg',
  'oda_4/oda4-8-min.jpg',
  'oda_4/oda4-9-min.jpg',
  'oda_4/oda4-10-min.jpg',
  'oda_4/wcd-1-min.jpg',
  'oda_4/wcd-2-min.jpg',
  'oda_4/wcd-3-min.jpg',
];
